import { Request, Response } from "express";
import { Types } from "mongoose";
import Receipt from "../models/Receipt";
import Plot from "../models/Plot";
import { AuthRequest } from "../middleware/auth.middleware";
import { sendSuccess, sendError } from "../utils/responseHelper";
import {
  generateReceiptPDF,
  fetchOrRebuildReceiptPdf,
} from "../utils/receiptPdfGenerator";
import { deleteFromCloudinary } from "../lib/deleteFromCloudinary";

const CURRENT_YEAR = new Date().getFullYear();

/**
 * GET /receipts
 * Query: page, limit, q (search), plot_id, year, from, to, voided
 *
 * Lists receipts newest-first with pagination. `q` matches receiptNumber,
 * block, plot, or owner name (case-insensitive); `year` and `from`/`to` (on
 * paymentDate) narrow an archive that keeps growing.
 */
export const getReceipts = async (req: Request, res: Response): Promise<void> => {
  try {
    const page = parseInt(req.query.page as string) || 1;
    const limit = parseInt(req.query.limit as string) || 20;
    const q = String(req.query.q || "").trim();

    const filter: any = {};

    // One plot's own receipts, for the plot detail view. Filtered on `plotRef`
    // rather than the snapshotted plot/block strings so a renamed or renumbered
    // plot keeps its history.
    const plotId = String(req.query.plot_id || req.query.plotId || "").trim();
    if (plotId) {
      if (!Types.ObjectId.isValid(plotId)) {
        sendError(res, "Invalid plot id", 400);
        return;
      }
      filter.plotRef = new Types.ObjectId(plotId);
    }

    // Year and date range. A free-text search across four fields cannot use an
    // index, so on an archive that grows for twenty years these narrow the scan
    // to something an index can answer. "Receipts for plot 374 in 2031" is the
    // question an admin actually asks.
    const year = parseInt(String(req.query.year || ""), 10);
    if (Number.isFinite(year) && year > 1900) filter.year = year;

    const from = String(req.query.from || "").trim();
    const to = String(req.query.to || "").trim();
    if (from || to) {
      const range: Record<string, Date> = {};
      const fromDate = from ? new Date(from) : null;
      const toDate = to ? new Date(to) : null;
      if (fromDate && !isNaN(fromDate.getTime())) range.$gte = fromDate;
      if (toDate && !isNaN(toDate.getTime())) {
        // Inclusive of the end date: a range typed as 01–31 January must include
        // everything issued on the 31st, not stop at its first second.
        toDate.setHours(23, 59, 59, 999);
        range.$lte = toDate;
      }
      if (Object.keys(range).length) filter.paymentDate = range;
    }

    if (String(req.query.voided || "") === "true") filter.isVoided = true;
    if (String(req.query.voided || "") === "false") filter.isVoided = { $ne: true };

    if (q) {
      const rx = new RegExp(q.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "i");
      filter.$or = [
        { receiptNumber: rx },
        { blockNo: rx },
        { plotNo: rx },
        { ownerName: rx },
      ];
    }

    const [receipts, total] = await Promise.all([
      Receipt.find(filter)
        .sort({ createdAt: -1 })
        .skip((page - 1) * limit)
        .limit(limit)
        // ownerPhone rides along so the admin UI can offer "Send via WhatsApp"
        // without a second request per row.
        .populate("plotRef", "plotBlock ownerName ownerPhone")
        .populate("generatedBy", "name email")
        .lean(),
      Receipt.countDocuments(filter),
    ]);

    sendSuccess(res, receipts, "Receipts fetched", 200, {
      page,
      limit,
      total,
      totalPages: Math.ceil(total / limit),
    });
  } catch (error: any) {
    sendError(res, "Failed to fetch receipts", 500, error.message);
  }
};

/**
 * POST /receipts
 * Body: { plotRef, amount, month, year, language, paymentDate, societyName }
 *
 * Creates a receipt for the selected plot. Block / plot / owner are taken from
 * the plot record (authoritative — not trusted from the client). The receipt
 * is verified on creation. receiptNumber is auto-generated by the model hook.
 */
export const createReceipt = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const b = req.body || {};

    const amount = Number(b.amount);
    if (!Number.isFinite(amount) || amount < 0) {
      sendError(res, "A valid amount is required", 400);
      return;
    }

    if (!b.plotRef) {
      sendError(res, "Please select a plot", 400);
      return;
    }
    const plot = await Plot.findById(b.plotRef).lean();
    if (!plot) {
      sendError(res, "Selected plot not found", 400);
      return;
    }

    const year = parseInt(b.year) || CURRENT_YEAR;
    const language: "en" | "ur" = b.language === "ur" ? "ur" : "en";

    const receipt = await Receipt.create({
      year,
      month: b.month || "",
      language,
      plotRef: plot._id,
      blockNo: plot.block || "",
      plotNo: plot.plotNumber || "",
      ownerName: plot.ownerName || "",
      amount,
      paymentDate: b.paymentDate ? new Date(b.paymentDate) : new Date(),
      dateFrom: b.dateFrom ? new Date(b.dateFrom) : null,
      dateTo: b.dateTo ? new Date(b.dateTo) : null,
      societyName: b.societyName || "KKB Housing Society",
      isVerified: true,
      generatedBy: req.admin?.id,
    });

    // Generate PDF immediately so filePath (Cloudinary URL) is available right away.
    try {
      const { url } = await generateReceiptPDF(receipt);
      receipt.filePath = url;
      await receipt.save();
    } catch (err) {
      console.warn("[receipt] Eager PDF generation failed:", (err as Error).message);
    }

    sendSuccess(res, receipt, "Receipt created", 201);
  } catch (error: any) {
    if (error?.code === 11000) {
      sendError(res, "Receipt number collision, please retry", 409, error.message);
      return;
    }
    sendError(res, "Failed to create receipt", 500, error.message);
  }
};

/**
 * GET /receipts/:id — single receipt detail.
 */
export const getReceipt = async (req: Request, res: Response): Promise<void> => {
  try {
    const receipt = await Receipt.findById(req.params.id)
      .populate("plotRef", "plotBlock ownerName ownerPhone block plotNumber")
      .populate("generatedBy", "name email")
      .lean();
    if (!receipt) {
      sendError(res, "Receipt not found", 404);
      return;
    }
    sendSuccess(res, receipt, "Receipt fetched");
  } catch (error: any) {
    sendError(res, "Failed to fetch receipt", 500, error.message);
  }
};

/**
 * GET /receipts/:id/pdf — stream the receipt PDF.
 * Public (no auth) so the admin UI can open it via window.open without
 * attaching the bearer token — mirrors the notice download endpoint.
 *
 * THE STORED PDF IS A CACHE, NOT THE RECORD. Every field the slip prints lives
 * on the receipt document itself (see receiptPdfGenerator — it reads no Plot and
 * no Payment), so the file can always be rebuilt. That is what lets old PDFs be
 * purged from storage after a year to keep the hosting bill flat: a purged
 * receipt is a cache miss, not a loss.
 *
 * So a missing or unreachable object must never be an error. Previously it was:
 * the fetch threw and the endpoint answered 500 for good, even though the data
 * was intact. Now anything short of a genuine rendering failure regenerates.
 */
export const generatePDF = async (req: Request, res: Response): Promise<void> => {
  try {
    const receipt = await Receipt.findById(req.params.id);
    if (!receipt) {
      sendError(res, "Receipt not found", 404);
      return;
    }

    const { object: obj } = await fetchOrRebuildReceiptPdf(receipt);

    const fileName = `${receipt.receiptNumber || "receipt"}.pdf`;
    res.setHeader("Content-Type", obj.contentType || "application/pdf");
    if (obj.contentLength) res.setHeader("Content-Length", String(obj.contentLength));
    res.setHeader("Content-Disposition", `inline; filename="${fileName}"`);
    obj.body.pipe(res);
    obj.body.on("error", () => {
      if (!res.headersSent) sendError(res, "Failed to stream receipt PDF", 500);
      else res.end();
    });
  } catch (error: any) {
    console.error('[receipt] generatePDF failed:', error);
    sendError(res, "Failed to generate receipt PDF", 500, error.message);
  }
};

/**
 * POST /receipts/:id/void — cancel a receipt without destroying it.
 *
 * Replaces the old hard delete. A receipt number has already been handed to an
 * owner, so the record has to survive being wrong: deleting it left a permanent
 * hole in the KKB-YYYY-#### series, orphaned the cash-book entry's `receiptRef`,
 * and destroyed the only proof of what was collected. Voiding keeps the row,
 * marks it cancelled, and re-renders the slip with a VOID stamp so the paper and
 * the database agree.
 *
 * Note this voids the RECEIPT only. When the payment itself was a mistake, void
 * the collection in Accounts instead — that reverses the dues and the income and
 * voids this receipt along with them.
 */
export const voidReceipt = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const receipt = await Receipt.findById(req.params.id);
    if (!receipt) {
      sendError(res, "Receipt not found", 404);
      return;
    }
    if (receipt.isVoided) {
      sendSuccess(res, receipt, "Receipt was already voided");
      return;
    }

    const reason = String(req.body?.reason || "").trim();
    receipt.isVoided = true;
    receipt.isVerified = false;
    receipt.voidReason = reason;

    // Drop the cached PDF so the next request re-renders it with the stamp.
    const stale = receipt.filePath;
    receipt.filePath = "";
    await receipt.save();

    if (stale) {
      deleteFromCloudinary(stale).catch((e) =>
        console.warn("[receipt.void] Cloudinary cleanup failed:", e?.message),
      );
    }

    sendSuccess(res, receipt, "Receipt voided");
  } catch (error: any) {
    sendError(res, "Failed to void receipt", 500, error.message);
  }
};
