import { Request, Response } from "express";
import Receipt from "../models/Receipt";
import Plot from "../models/Plot";
import { AuthRequest } from "../middleware/auth.middleware";
import { sendSuccess, sendError } from "../utils/responseHelper";
import { generateReceiptPDF } from "../utils/receiptPdfGenerator";
import { getFromCloudinary } from "../lib/getFromCloudinary";
import { deleteFromCloudinary } from "../lib/deleteFromCloudinary";

const CURRENT_YEAR = new Date().getFullYear();

/**
 * GET /receipts
 * Query: page, limit, q (search)
 *
 * Lists receipts newest-first with pagination. `q` matches receiptNumber,
 * block, plot, or owner name (case-insensitive).
 */
export const getReceipts = async (req: Request, res: Response): Promise<void> => {
  try {
    const page = parseInt(req.query.page as string) || 1;
    const limit = parseInt(req.query.limit as string) || 20;
    const q = String(req.query.q || "").trim();

    const filter: any = {};
    if (q) {
      const rx = new RegExp(q.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "i");
      filter.$or = [
        { receiptNumber: rx },
        { blockNo: rx },
        { plotNo: rx },
        { ownerName: rx },
      ];
    }

    const [receipts, total] = await Promise.all([
      Receipt.find(filter)
        .sort({ createdAt: -1 })
        .skip((page - 1) * limit)
        .limit(limit)
        .populate("generatedBy", "name email")
        .lean(),
      Receipt.countDocuments(filter),
    ]);

    sendSuccess(res, receipts, "Receipts fetched", 200, {
      page,
      limit,
      total,
      totalPages: Math.ceil(total / limit),
    });
  } catch (error: any) {
    sendError(res, "Failed to fetch receipts", 500, error.message);
  }
};

/**
 * POST /receipts
 * Body: { plotRef, amount, month, year, language, paymentDate, societyName }
 *
 * Creates a receipt for the selected plot. Block / plot / owner are taken from
 * the plot record (authoritative — not trusted from the client). The receipt
 * is verified on creation. receiptNumber is auto-generated by the model hook.
 */
export const createReceipt = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const b = req.body || {};

    const amount = Number(b.amount);
    if (!Number.isFinite(amount) || amount < 0) {
      sendError(res, "A valid amount is required", 400);
      return;
    }

    if (!b.plotRef) {
      sendError(res, "Please select a plot", 400);
      return;
    }
    const plot = await Plot.findById(b.plotRef).lean();
    if (!plot) {
      sendError(res, "Selected plot not found", 400);
      return;
    }

    const year = parseInt(b.year) || CURRENT_YEAR;
    const language: "en" | "ur" = b.language === "ur" ? "ur" : "en";

    const receipt = await Receipt.create({
      year,
      month: b.month || "",
      language,
      plotRef: plot._id,
      blockNo: plot.block || "",
      plotNo: plot.plotNumber || "",
      ownerName: plot.ownerName || "",
      amount,
      paymentDate: b.paymentDate ? new Date(b.paymentDate) : new Date(),
      dateFrom: b.dateFrom ? new Date(b.dateFrom) : null,
      dateTo: b.dateTo ? new Date(b.dateTo) : null,
      societyName: b.societyName || "KKB Housing Society",
      isVerified: true,
      generatedBy: req.admin?.id,
    });

    // Generate PDF immediately so filePath (Cloudinary URL) is available right away.
    try {
      const { url } = await generateReceiptPDF(receipt);
      receipt.filePath = url;
      await receipt.save();
    } catch (err) {
      console.warn("[receipt] Eager PDF generation failed:", (err as Error).message);
    }

    sendSuccess(res, receipt, "Receipt created", 201);
  } catch (error: any) {
    if (error?.code === 11000) {
      sendError(res, "Receipt number collision, please retry", 409, error.message);
      return;
    }
    sendError(res, "Failed to create receipt", 500, error.message);
  }
};

/**
 * GET /receipts/:id — single receipt detail.
 */
export const getReceipt = async (req: Request, res: Response): Promise<void> => {
  try {
    const receipt = await Receipt.findById(req.params.id)
      .populate("plotRef", "plotBlock ownerName block plotNumber")
      .populate("generatedBy", "name email")
      .lean();
    if (!receipt) {
      sendError(res, "Receipt not found", 404);
      return;
    }
    sendSuccess(res, receipt, "Receipt fetched");
  } catch (error: any) {
    sendError(res, "Failed to fetch receipt", 500, error.message);
  }
};

/**
 * GET /receipts/:id/pdf — stream the receipt PDF from Cloudinary.
 * Public (no auth) so the admin UI can open it via window.open without
 * attaching the bearer token — mirrors the notice download endpoint.
 *
 * The PDF is generated and uploaded to Cloudinary lazily on the first request
 * and the URL is cached on `receipt.filePath`; subsequent requests stream the
 * cached object directly. Receipts are immutable (no edit endpoint), so the
 * cache never goes stale.
 */
export const generatePDF = async (req: Request, res: Response): Promise<void> => {
  try {
    const receipt = await Receipt.findById(req.params.id);
    if (!receipt) {
      sendError(res, "Receipt not found", 404);
      return;
    }

    // Generate + upload on first request; cache the URL on the document.
    if (!receipt.filePath) {
      const { url } = await generateReceiptPDF(receipt);
      receipt.filePath = url;
      await receipt.save();
    }

    const fileName = `${receipt.receiptNumber || "receipt"}.pdf`;
    const obj = await getFromCloudinary(receipt.filePath);

    res.setHeader("Content-Type", obj.contentType || "application/pdf");
    if (obj.contentLength) res.setHeader("Content-Length", String(obj.contentLength));
    res.setHeader("Content-Disposition", `inline; filename="${fileName}"`);
    obj.body.pipe(res);
    obj.body.on("error", () => {
      if (!res.headersSent) sendError(res, "Failed to stream receipt PDF", 500);
      else res.end();
    });
  } catch (error: any) {
    console.error('[receipt] generatePDF failed:', error);
    sendError(res, "Failed to generate receipt PDF", 500, error.message);
  }
};

/**
 * DELETE /receipts/:id — hard delete (also removes the cached PDF from Cloudinary).
 */
export const deleteReceipt = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const receipt = await Receipt.findByIdAndDelete(req.params.id);
    if (!receipt) {
      sendError(res, "Receipt not found", 404);
      return;
    }
    // Best-effort cleanup of the cached PDF; don't fail the delete on error.
    if (receipt.filePath) {
      deleteFromCloudinary(receipt.filePath).catch((e) =>
        console.warn("[receipt.delete] Cloudinary cleanup failed:", e?.message),
      );
    }
    sendSuccess(res, { _id: receipt._id }, "Receipt deleted");
  } catch (error: any) {
    sendError(res, "Failed to delete receipt", 500, error.message);
  }
};
